/* DO NOT EDIT THIS FILE - it is machine generated */
#include<iostream>
#include <jni.h>
#include<opencv2/opencv.hpp>
#include<opencv2/highgui/highgui.hpp>

#include<dlib/dlib/opencv.h>
#include<dlib/dlib/image_processing/frontal_face_detector.h>
#include<dlib/dlib/image_processing/render_face_detections.h>
#include<dlib/dlib/image_processing.h>

using namespace cv;
using namespace std;
using namespace dlib;
/* Header for class com_example_abhishekyadav_jjdlibvideofeaturedetector_1_NativeClass */

#ifndef _Included_com_example_abhishekyadav_jjdlibvideofeaturedetector_1_NativeClass
#define _Included_com_example_abhishekyadav_jjdlibvideofeaturedetector_1_NativeClass
#ifdef __cplusplus
extern "C" {
#endif

void faceDetectionDlib(Mat& img, Mat& dst);
void renderToMat(std::vector<full_object_detection>& dets, Mat& dst);

JNIEXPORT jstring JNICALL Java_com_example_abhishekyadav_jjdlibvideofeaturedetector_11_NativeClass_initDetectors
  (JNIEnv *env, jclass);

/*
 * Class:     com_example_abhishekyadav_jjdlibvideofeaturedetector_1_NativeClass
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_abhishekyadav_jjdlibvideofeaturedetector_11_NativeClass_getMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_example_abhishekyadav_jjdlibvideofeaturedetector_1_NativeClass
 * Method:    LandmarkDetection
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_abhishekyadav_jjdlibvideofeaturedetector_11_NativeClass_LandmarkDetection
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
